image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
  - build
  - validate
  - test

variables:
  GITLAB_DOCKER_PROXY: gitlab.education.tbank.ru:443/backend-academy-dotnet-2025/lecture-materials/dependency_proxy/containers
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  DOTNET_NOLOGO: "1"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never

cache:
  key: "nuget-$CI_COMMIT_REF_SLUG"
  paths:
    - .nuget/packages/
  policy: pull-push

.default_dotnet_job:
  before_script:
    - dotnet --info
    - dotnet restore

build:
  stage: build
  extends: .default_dotnet_job
  script:
    - dotnet build --no-restore

linter:
  stage: validate
  extends: .default_dotnet_job
  script:
    - dotnet format --verify-no-changes --no-restore

.test_job:
  stage: test
  extends: .default_dotnet_job
  needs:
    - job: build
      artifacts: false
  script:
    - dotnet test --no-restore --filter "$TEST_FILTER"

bot_unit_test:
  extends: .test_job
  variables:
    TEST_FILTER: "Module=Bot&Category=Unit"

scrapper_unit_test:
  extends: .test_job
  variables:
    TEST_FILTER: "Module=Scrapper&Category=Unit"

shared_unit_test:
  extends: .test_job
  variables:
    TEST_FILTER: "Module=Shared&Category=Unit"
    
aiagent_unit_test:
  extends: .test_job
  variables:
    TEST_FILTER: "Module=AiAgent&Category=Unit"

shared_integration_test:
  extends: .test_job
  variables:
    TEST_FILTER: "Module=Shared&Category=Integration"

.dind_test_job:
  extends: .test_job
  tags:
    - dind
  services:
    - name: docker:29.0.1-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    TESTCONTAINERS_RYUK_DISABLED: "true"
  before_script:
    - dotnet --info
    - dotnet restore
    - apt-get update
    - apt-get install -y ca-certificates curl gnupg
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc
    - . /etc/os-release
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian ${VERSION_CODENAME} stable" > /etc/apt/sources.list.d/docker.list
    - apt-get update
    - apt-get install -y docker-ce-cli
    - echo "$CI_JOB_TOKEN" | docker login gitlab.education.tbank.ru:443 -u gitlab-ci-token --password-stdin
    - docker version

bot_integration_test:
  extends: .dind_test_job
  variables:
    TEST_FILTER: "Module=Bot&Category=Integration"

scrapper_integration_test:
  extends: .dind_test_job
  variables:
    TEST_FILTER: "Module=Scrapper&Category=Integration"
      

aiagent_integration_test:
  extends: .dind_test_job
  variables:
    TEST_FILTER: "Module=AiAgent&Category=Integration"