<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\LinkTracker.Bot.Application\LinkTracker.Bot.Application.csproj"/>
        <ProjectReference Include="..\LinkTracker.Shared\LinkTracker.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Telegram.Bot" Version="22.9.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5"/>
        <PackageReference Include="Grpc.AspNetCore" Version="2.76.0"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
