<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\LinkTracker.Scrapper.Storage.Abstractions\LinkTracker.Scrapper.Storage.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.72"/>
        <PackageReference Include="Npgsql" Version="10.0.2"/>
    </ItemGroup>

</Project>