<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\LinkTracker.Scrapper.Contracts\LinkTracker.Scrapper.Contracts.csproj"/>
        <ProjectReference Include="..\LinkTracker.Scrapper.Storage.Abstractions\LinkTracker.Scrapper.Storage.Abstractions.csproj"/>
        <ProjectReference Include="..\LinkTracker.Shared\LinkTracker.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5"/>
    </ItemGroup>

</Project>